import React, {useState,useRef,useEffect} from 'react';
import {MessageSquare, ChevronDown, ArrowUpRight, Send, Gift, X, ShieldCheck} from 'lucide-react';
import {Avatar, Btc} from './ui';
import {MESSAGES} from './data';
export default function Chat({game,openModal,visible,setVisible}) {
 const [messages,setMessages]=useState(MESSAGES); const [text,setText]=useState(''); const bottom=useRef(null); const [sent,setSent]=useState(false);
 useEffect(()=>{if(sent) bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[messages,sent]);
 function send(e){e.preventDefault(); if(!text.trim())return; if(!game.connected){openModal('wallet');return;} setMessages(m=>[...m,{name:'You',level:1,color:'#f8ac35',text:text.trim().slice(0,180),time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}].slice(-50));setText('');setSent(true);}
 return <aside className={`chat-sidebar ${visible?'chat-open':''}`}><div className="chat-heading"><span><MessageSquare size={17}/>The chat room</span><button className="icon-button chat-desktop-close" aria-label="Close chat" onClick={()=>setVisible(false)}><X size={15}/></button></div><div className="chat-subhead"><button onClick={()=>game.notify('You’re in the English demo chat.','info')}>English <ChevronDown size={12}/></button><span><i className="network-dot"/>128 online</span></div><div className="rain-card"><div className="rain-icon"><Gift size={24}/></div><div><span>GOOD THINGS DROP.</span><strong>The next rain is coming</strong></div><div className="rain-bottom"><span><Btc/>0.0025 <small>BTC</small></span><button onClick={()=>openModal('rewards')}>Get ready <ArrowUpRight size={13}/></button></div></div><div className="chat-date"><span/>TODAY<span/></div><div className="messages">{messages.map((m,i)=><div className="chat-message" key={i}><Avatar name={m.name} color={m.color} size="tiny"/><div className="message-main"><div className="message-meta"><strong>{m.name}</strong><span className="level">{m.level}</span><time>{m.time}</time></div><p>{m.text}</p></div></div>)}<div className="chat-event"><TrophyIcon/><span><b>whale.btc</b> won <strong>0.0182 BTC</strong><br/><small>in the jackpot. That’s a nice catch.</small></span></div><div ref={bottom}/></div><div className="chat-compose"><form onSubmit={send}><input aria-label="Chat message" placeholder="Say something nice…" maxLength={180} value={text} onChange={e=>setText(e.target.value)}/><button aria-label="Send message" type="submit"><Send size={15}/></button></form><div className="chat-compose-bottom"><span><ShieldCheck size={12}/>Keep it good.</span><button onClick={()=>openModal('chatRules')}>Chat rules <ArrowUpRight size={11}/></button></div><div className="chat-demo">Demo community · messages stay on this device</div></div></aside>;
}
function TrophyIcon(){return <span className="chat-event-icon"><Gift size={16}/></span>;}
