import React, {useState} from 'react';
import {Wallet,ArrowRight,Bitcoin,ShieldCheck,Plus,Coins,Copy,Check,Gift,ExternalLink,Clock3,Trophy,Sparkles,ArrowUpRight} from 'lucide-react';
import {Modal,Btc,Coin,Avatar} from './ui';
import {fmt,readStorage} from './data';
import WalletConnect,{shorten} from './WalletConnect';
export default function Dialogs({modal,close,game}) {
 const [amount,setAmount]=useState(String(modal.data?.amount||0.001)); const [side,setSide]=useState('heads'); const [claimed,setClaimed]=useState(()=>readStorage('bpot-reward-date','')===new Date().toISOString().slice(0,10)); const [copied,setCopied]=useState(false);
 const type=modal.type; const flip=game.activeFlip;
 const titles={wallet:game.connected?'Your Bitcoin balance':'Your seat at the table.',createFlip:'Two sides. One winner.',joinFlip:'Ready to call it?',history:'Your game history',fairness:'A fair shot. By design.',rewards:'A little extra to play with.',affiliates:'Good company pays off.',token:'The next chapter of Bpot.',support:'How can we help?',community:'The community starts here.',chatRules:'Keep the chat room good.',howTo:'Welcome to the playground.',terms:'The demo, explained.'};
 function startFlip(){const data=modal.data; if(!game.connected){game.connect();return;} const chosen=data?(data.side==='heads'?'tails':'heads'):side;game.playFlip(Number(amount),chosen,data?.name,data?.id);}
 function claim(){if(!game.connected){game.notify('Connect your demo wallet to claim your reward.','error');return;} if(claimed)return; game.setBalance(b=>b+0.001);localStorage.setItem('bpot-reward-date',JSON.stringify(new Date().toISOString().slice(0,10)));setClaimed(true);game.notify('Daily reward claimed: 0.0010 demo BTC.');}
 async function copy(){try{const url=new URL(location.href);url.searchParams.set('ref','bpot-demo');await navigator.clipboard.writeText(url.href);setCopied(true);}catch{game.notify('Copy the referral link from the field below.','info');}}
 function finish(){if(flip&&flip.phase!=='result'){game.notify('Your flip is playing. The result will be saved in History.','info');}if(flip?.phase==='result')game.setActiveFlip(null);close();}
 return <Modal title={flip&&['createFlip','joinFlip'].includes(type)?flip.phase==='result'?(flip.won?'That’s your Bitcoin.':'The other side takes it.'):'Your flip is in play.':titles[type]||'Bpot'} eyebrow={type==='token'?'THE BPOT TOKEN':type==='history'?'YOUR SESSION':'THE BITCOIN PLAYGROUND'} close={finish} wide={type==='history'}>
 {type==='wallet'&&<>{!game.connected?<WalletConnect game={game} close={close}/>:<><p className="modal-description">Your demo BTC is ready for jackpots and head-to-head flips.</p><div className="wallet-balance"><span>AVAILABLE BALANCE</span><strong><Btc/>{fmt(game.balance)}<small>BTC</small></strong><span className="demo-balance-note">DEMO CREDITS · NO MONETARY VALUE</span></div><div className="wallet-connected-row"><span className="wallet-mark small" style={{'--wallet-color':'#f4bc5a'}}>{(game.wallet||'D')[0]}</span><span className="wallet-meta"><strong>{game.wallet||'Demo wallet'}</strong><small>{game.address?shorten(game.address):'Demo session · no chain connection'}</small></span><button className="wallet-disconnect" onClick={()=>{game.disconnect();close();}}>Disconnect</button></div><button className="primary-button modal-primary" onClick={game.fund}><Plus size={17}/>Add 0.1000 demo BTC</button><div className="modal-note"><ShieldCheck size={15}/><span>Bpot never requests a seed phrase or moves funds. All wagers are demo credits.</span></div></>}</>}
 {['createFlip','joinFlip'].includes(type)&&<>{flip?<div className="flip-result"><span className="result-status">{flip.phase==='matching'?'FINDING YOUR OPPONENT':flip.phase==='flipping'?'THE COIN IS IN THE AIR':flip.won?'YOU WON':'BETTER LUCK NEXT FLIP'}</span><Coin side={flip.result||flip.side} animate={flip.phase==='flipping'}/><div className="result-players"><span><Avatar name="You" color="#f8ac35" size="small"/>You</span><span className="vs">vs</span><span><Avatar name={flip.opponent} size="small"/>{flip.opponent}</span></div>{flip.phase==='result'?<><strong className={`result-amount ${flip.won?'gold':''}`}>{flip.won?'+':'−'} {fmt(flip.won?flip.amount:flip.amount)} BTC</strong><p>The coin landed on <b>{flip.result}</b>. {flip.won?`${fmt(flip.amount*2)} demo BTC returned to your balance.`:'Your wager went to the opponent.'}</p><button className="primary-button modal-primary" onClick={()=>game.setActiveFlip(null)}>Play another flip <ArrowRight size={16}/></button></>:<p>{flip.phase==='matching'?'A demo opponent is taking the other side.':'Heads or tails. Both have a 50% chance.'}</p>}</div>:<><p className="modal-description">{type==='joinFlip'?`Take the ${modal.data.side==='heads'?'tails':'heads'} side against ${modal.data.name}. Winner takes the whole pot.`:'Choose your side and wager. A demo opponent will match your bet.'}</p><div className="side-selector">{['heads','tails'].map(s=><button key={s} disabled={type==='joinFlip'} className={(type==='joinFlip'?(modal.data.side==='heads'?'tails':'heads'):side)===s?'selected':''} onClick={()=>setSide(s)}><span className={`small-coin ${s}`}><Bitcoin size={25}/></span><strong>{s[0].toUpperCase()+s.slice(1)}</strong><span>50% chance</span></button>)}</div><div className="input-label"><label htmlFor="flip-amount">Your wager</label><span>Balance: {fmt(game.balance)} BTC</span></div><div className="amount-input"><Btc/><input id="flip-amount" type="number" min="0.0001" step="0.0001" disabled={type==='joinFlip'} value={amount} onChange={e=>setAmount(e.target.value)}/><span>BTC</span></div><div className="potential-return"><span>Winner takes</span><strong><Btc/>{fmt(Number(amount)*2)} BTC</strong></div><button className="primary-button modal-primary" onClick={startFlip}><Coins size={16}/>{!game.connected?'Connect demo wallet':type==='joinFlip'?'Join this flip':'Create coinflip'}<ArrowRight size={16}/></button><p className="modal-smallprint">Simulated PvP · 0% demo fee · Instant demo settlement</p></>}</>}
 {type==='history'&&<>{game.history.length?<><p className="modal-description">Your completed rounds on this device.</p><div className="history-table"><div className="history-table-header"><span>GAME</span><span>WAGER</span><span>RETURNED</span><span>RESULT</span></div>{game.history.map((h,i)=><div key={`${h.id}-${i}`}><span><strong>{h.game}</strong><small>{new Date(h.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></span><span>{fmt(h.amount)} BTC</span><span>{fmt(h.payout)} BTC</span><b className={h.won?'win-chip':'loss-chip'}>{h.won?'Won':'Lost'}</b></div>)}</div></>:<div className="empty-state spacious"><Clock3 size={38}/><h3>Your first round is waiting.</h3><p>Join a jackpot or play a coinflip. Completed games and payouts will appear here.</p><button className="primary-button" onClick={close}>Back to the playground <ArrowRight size={16}/></button></div>}</>}
 {type==='fairness'&&<><p className="modal-description">Simple odds you can understand before you play.</p><div className="info-block"><CircleIcon/><div><h3>Jackpot: your share is your chance</h3><p>A 0.001 BTC contribution to a 0.010 BTC pot gives you a 10% chance. Every entry is included in the draw.</p></div></div><div className="info-block"><Coins size={22}/><div><h3>Coinflip: exactly two sides</h3><p>Heads and tails each have a 50% chance. Both players contribute the same amount, and the winner receives the full pot in this demo.</p></div></div><div className="notice-panel"><ShieldCheck size={20}/><p>This prototype uses your browser’s cryptographic random generator. It is not an on-chain or independently verifiable fairness system. Seed commitments, public verification, and settlement are part of the future production integration.</p></div></>}
 {type==='rewards'&&<><div className="reward-visual"><Gift size={55}/><span>YOUR DAILY DROP</span><strong>0.0010 <small>BTC</small></strong></div><p className="modal-description center">A little Bitcoin energy, on us. Claim free demo credits once each UTC day.</p><button className="primary-button modal-primary" disabled={claimed} onClick={claim}>{claimed?<Check size={17}/>:<Gift size={17}/>} {claimed?'Claimed — see you tomorrow':'Claim daily demo reward'}</button><p className="modal-smallprint">Rain events and token-holder rewards are coming later.</p></>}
 {type==='affiliates'&&<><p className="modal-description">Bring your people to the playground. This is a preview of your future affiliate dashboard.</p><div className="affiliate-stats"><div><span>Friends invited</span><strong>0</strong></div><div><span>Rewards earned</span><strong>0 <small>BTC</small></strong></div></div><label className="input-label" htmlFor="referral-link">Your demo referral link</label><div className="referral-link"><input id="referral-link" readOnly value={`${location.origin}${location.pathname}?ref=bpot-demo`}/><button onClick={copy} aria-label="Copy referral link">{copied?<Check size={17}/>:<Copy size={17}/>}</button></div><p className="modal-smallprint">Referral tracking and reward rates will be announced with the token launch.</p></>}
 {type==='token'&&<><div className="token-pair"><Coin/><span>×</span><div className="future-token">b<span>.</span></div></div><p className="modal-description center">A new coin. Paired with Bitcoin.<br/>Built for the Bpot ecosystem.</p><div className="token-detail"><span>Trading pair</span><strong>BPOT / BTC <small>planned</small></strong></div><div className="token-detail"><span>Token details</span><strong>To be announced</strong></div><div className="notice-panel"><Sparkles size={20}/><p>The final ticker, chain, utility, and launch details will be defined next. No token is available to buy in this preview.</p></div></>}
 {type==='howTo'&&<><p className="modal-description">Two ways to play. One Bitcoin playground.</p><div className="howto-step"><b>1</b><div><h3>Take your seat</h3><p>Connect a demo wallet to start with 0.1000 BTC in play credits.</p></div></div><div className="howto-step"><b>2</b><div><h3>Find your game</h3><p>Join the jackpot for a chance at the entire pot, or call heads or tails in a 1v1 coinflip.</p></div></div><div className="howto-step"><b>3</b><div><h3>Let it play out</h3><p>Watch the draw and collect any demo winnings automatically. Your results are saved in History.</p></div></div><button className="primary-button modal-primary" onClick={close}>Let’s play <ArrowRight size={17}/></button></>}
 {type==='support'&&<div className="faq-list">{[['How do I start?','Use Connect wallet in the header. The demo wallet starts with 0.1000 BTC in play credits.'],['Can I deposit or withdraw real Bitcoin?','This is an interactive prototype. Deposits, withdrawals, and real wallet connections are not enabled.'],['Where are my game results?','Open History beside Jackpot. Completed jackpots you entered and all your coinflips are saved on this device.'],['How do I top up my balance?','Click your wallet balance in the header, then Add 0.1000 demo BTC.'],['When does the token launch?','The token ticker, chain, pairing, and launch details have not yet been announced.']].map(([q,a])=><details key={q}><summary>{q}<Plus size={15}/></summary><p>{a}</p></details>)}</div>}
 {type==='community'&&<><p className="modal-description">The official Bpot community channels will be announced with the launch. For now, try the demo chat room and explore the games.</p><button className="primary-button modal-primary" onClick={close}>Back to Bpot <ArrowRight size={16}/></button></>}
 {type==='chatRules'&&<div className="rules-list"><p>Be welcoming. Keep the conversation about the games and the community.</p><p>No spam, harassment, referral flooding, or requests for private keys.</p><p>Never share personal information or wallet recovery phrases in chat.</p><div className="notice-panel"><ShieldCheck size={20}/><p>This is a local demo chat. Sample messages and players are fictional, and your messages stay on this device.</p></div></div>}
 {type==='terms'&&<><p className="modal-description">Bpot is currently an interactive design prototype for adults aged 18 and over.</p><div className="rules-list"><p>All balances, wagers, winnings, players, activity, and statistics are simulated. Demo BTC has no monetary value and cannot be withdrawn.</p><p>USD estimates use a fixed illustrative exchange rate. No live market data or real token conversion is connected.</p><p>Your demo balance and completed game history are stored in this browser. Production terms will be defined before real-money functionality is introduced.</p></div></>}
 </Modal>;
}
function CircleIcon(){return <span className="circle-info-icon"><Bitcoin size={22}/></span>;}
